custom_stopwords = [
'katakan',  'kinilah', 'mempergunakan', 'mengingatkan', 'bolehkah', 'pun', 'sekaligus', 'jangan', 'kiranya', 'setiap'
'melihat', 'kapankah', 'diucapkannya', 'dikatakannya', 'seingat', 'besar', 'benarkah', 'seperti', 'tentu', 'tetapi', 
'ditanyai', 'cara', 'mengerjakan', 'sebaik-baiknya', 'lalu', 'sekecil', 'jangankan', 'mempunyai', 'berada', 'kemungkinan', 
'janganlah', 'memisalkan', 'seseorang', 'sebagai', 'secukupnya', 'ditunjuknya', 'berujar', 'sesuatunya', 'tanyanya', 
'bahwa', 'bagaimanakah', 'disebutkannya', 'menantikan', 'bagi', 'terhadap', 'sekali', 'ditandaskan', 'memungkinkan', 'dirinya', 
'tetap', 'pastilah', 'sebagaimana', 'bagaimana', 'gimana', 'bisa', 'belakang', 'cukupkah', 'jauh', 'memang', 'namun', 'semampunya', 
'dipersoalkan', 'bagaikan', 'dituturkan', 'rata', 'menanti-nanti', 'kitalah', 'sejumlah', 'bagai', 'tampaknya', 'lagi', 
'diucapkan', 'perlukah', 'semata-mata', 'kembali', 'disini', 'katanya', 'persoalan', 'bakal', 'hampir', 'dipunyai', 'sebelum', 
'seharusnya', 'dijawab', 'entahlah', 'seusai', 'mengingat', 'ditunjukkan', 'suatu', 'dimaksud', 'maksud', 'khususnya', 'tentulah', 
'ataukah', 'tentang', 'sejak', 'macam', 'seolah-olah', 'pertama', 'bermacam-macam', 'entah', 'mengibaratkannya', 'sebegini', 
'mengibaratkan', 'ditujukan', 'cuma', 'berdatangan', 'meyakini', 'ada', 'menambahkan', 'tanya', 'mendatangkan', 
'ialah', 'sinilah', 'nyatanya', 'walau', 'saya', 'soal', 'menyiapkan', 'harus', 'padahal', 'sangatlah', 
'menunjuknya', 'kata', 'makanya', 'apabila', 'beri', 'guna', 'sementara', 'diberikan', 'agaknya', 'dimaksudnya', 'jikalau', 
'sepantasnya', 'menginginkan', 'ditanyakan', 'sesekali', 'percuma', 'kasus', 'lima', 'sesuatu', 'menyatakan', 'tapi',
'hendaklah', 'hal', 'sampai', 'dijelaskan', 'dalam', 'kamu', 'masalahnya', 'pada', 'bisakah', 'cukup', 'menghendaki', 
'bertanya', 'dibuatnya', 'terbanyak', 'diakhiri', 'meski', 'seorang', 'semasih', 'memerlukan', 'nanti', 'semata', 'menunjukkan', 
'apalagi', 'diperlukan', 'mungkin', 'nah', 'dapat', 'berikut', 'haruslah', 'terjadinya', 'dari', 'disebut', 'membuat', 
'didatangkan', 'kenapa', 'tandasnya', 'seringnya', 'balik', 'akankah', 'jelaskan', 'jelasnya', 'akhir', 'selaku', 'menjawab', 
'amat', 'mengatakan', 'banyak', 'kok', 'sebanyak', 'sajalah', 'sebutnya', 'ditanya', 'siapapun', 'termasuk', 'setengah', 
'tentunya', 'diberi', 'diperbuat', 'diakhirinya', 'ketika', 'mengenai', 'berkeinginan', 'kesampaian', 'begitulah', 'sudahlah', 
'serupa', 'mengucapkan', 'sebenarnya', 'sebabnya', 'dua', 'sesudah', 'diminta', 'siapa', 'mengatakannya', 'mulailah', 
'bahkan', 'luar', 'mengakhiri', 'masihkah', 'menggunakan', 'terlihat', 'supaya', 'hari', 'olehnya', 'dialah', 'kepada', 
'lainnya', 'artinya', 'selamanya', 'seperlunya', 'waduh', 'wahai', 'sedikit', 'di', 'semakin', 'dahulu', 'pihaknya', 'dia', 
'tahu', 'umumnya', 'benar', 'usah', 'tambahnya', 'diketahuinya', 'usai', 'diperkirakan', 'juga', 'hendak', 'inginkan', 
'ditambahkan', 'mirip', 'sering', 'dipastikan', 'kelamaan', 'serta', 'kelihatannya', 'menunjuki', 'kala', 'diibaratkannya', 
'terdapat', 'tertuju', 'sekalipun', 'keluar', 'adapun', 'kalau', 'setiba', 'biasa', 'berikutnya', 'bukannya', 'kemungkinannya', 
'bermula', 'lama', 'masih', 'ungkap', 'dimisalkan', 'terus', 'diingat', 'sesaat', 'ingin', 'memihak', 'sedang', 'selalu', 
'terkira', 'sebagainya', 'begitukah', 'dipertanyakan', 'kalaulah', 'apatah', 'mempertanyakan', 'memulai', 'andalah', 
'jawab', 'melainkan', 'menandaskan', 'ibu', 'menanya', 'terdahulu', 'teringat-ingat', 'sama-sama', 'ungkapnya', 
'masalah', 'memperkirakan', 'bertanya-tanya', 'apa', 'begitupun', 'baik', 'bekerja', 'apakah', 'punya', 'hingga', 'sebaik', 
'sempat', 'satu', 'terjadi', 'berlalu', 'yakni', 'setibanya', 'jelas', 'per', 'kepadanya', 'tak', 'berlebihan', 'disampaikan', 
'tidak', 'selanjutnya', 'dong', 'ikut', 'dituturkannya', 'datang', 'kan', 'kapanpun', 'misal', 'seluruhnya', 'demikian', 'itukah', 
'rupanya', 'jumlahnya', 'segalanya', 'selama', 'memperlihatkan', 'dimaksudkannya', 'sela', 'menjadi', 'sekurangnya', 'ibaratnya', 
'menyangkut', 'lanjut', 'bukankah', 'dikarenakan', 'sesama', 'diibaratkan', 'bersiap-siap', 'malahan', 'antar', 'masing-masing', 
'sesudahnya', 'sedemikian', 'sedikitnya', 'dijelaskannya', 'menurut', 'agar', 'kebetulan', 'dimulai', 'lebih', 'daripada', 
'dimintai', 'tiga', 'lewat', 'teringat', 'harusnya', 'katakanlah', 'dibuat', 'benarlah', 'berupa', 'mana', 'menyebutkan', 
'dipergunakan', 'seterusnya', 'mendatang', 'ingat-ingat', 'bulan', 'telah', 'masing', 'tempat', 'mengucapkannya', 'mendapatkan', 
'tegas', 'yakin', 'sekali-kali', 'penting', 'berawal', 'menanti', 'rasanya', 'semuanya', 'karena', 'berbagai', 'terhadapnya', 
'bahwasanya', 'lanjutnya', 'saatnya', 'sampai-sampai', 'terasa', 'mampukah', 'berikan', 'sejauh', 'bapak', 'umum', 'wong', 
'diungkapkan', 'terlebih', 'pantas', 'jelaslah', 'jika', 'sebetulnya', 'setempat', 'sehingga', 'dulu', 'pukul', 'bertutur', 
'bila', 'sebuah', 'pentingnya', 'diperbuatnya', 'kurang', 'memberi', 'tadi', 'sepihak', 'anda', 'berkehendak', 'ditunjukkannya', 
'ditegaskan', 'berjumlah', 'mendapat', 'tampak', 'pihak', 'ujarnya', 'tiba', 'tengah', 'aku', 'jadilah', 'waktunya', 'jumlah', 
'apaan', 'sekarang', 'diperlihatkan', 'misalkan', 'memberikan', 'akulah', 'nantinya', 'rasa', 'kini', 'sambil', 'meminta', 
'menyeluruh', 'diingatkan', 'atas', 'jadi', 'kira-kira', 'pasti', 'sebaiknya', 'merekalah', 'sebelumnya', 'inilah', 'belum', 
'saling', 'sama', 'semisal', 'dikira', 'beginilah', 'awalnya', 'diinginkan', 'asalkan', 'awal', 'kemudian', 'manakala', 
'berlainan', 'berarti', 'buat', 'kita', 'seenaknya', 'selain', 'sudah', 'keterlaluan', 'didapat', 'beginikah', 'asal', 'menuju', 
'dini', 'minta', 'dikatakan', 'keseluruhannya', 'sayalah', 'sesegera', 'demikianlah', 'menunjuk', 'baru', 'mengira', 'begini', 
'mendatangi', 'sudahkah', 'ke', 'mengetahui', 'pertanyaan', 'bukanlah', 'seolah', 'melalui', 'ternyata', 'enggak', 'atau', 
'siapakah', 'dengan', 'antara', 'segala', 'sekitarnya', 'tutur', 'mempersoalkan', 'dekat', 'sana', 'mengungkapkan', 'dimungkinkan', 
'bolehlah', 'dikerjakan', 'manalagi', 'tepat', 'keinginan', 'para', 'sebegitu', 'menanyakan', 'kecil', 'sekitar', 'berturut', 
'malah', 'siap', 'ucapnya', 'bukan', 'jawaban', 'bermacam', 'keseluruhan', 'tinggi', 'perlunya', 'memastikan', 'sejenak', 
'diantaranya', 'bersama', 'terdiri', 'sedangkan', 'maupun', 'ini', 'diketahui', 'berapakah', 'memintakan', 'setelah', 'semacam', 
'berkali-kali', 'karenanya', 'jawabnya', 'mengapa', 'diperlukannya', 'semaunya', 'tersampaikan', 'berapalah', 
'lagian', 'tegasnya', 'terutama', 'begitu', 'betulkah', 'sampaikan', 'semasa', 'semua', 'sendiri', 'diri', 'menaiki', 
'ibaratkan', 'menuturkan', 'tahun', 'antaranya', 'secara', 'sepanjang', 'terlalu', 'inikah', 'lah', 'makin', 'meskipun', 
'untuk', 'sebab', 'caranya', 'sini', 'semula', 'terjadilah', 'kapan', 'selama-lamanya', 'hendaknya', 'mau', 'pula', 'betul', 
'belumlah', 'dan', 'se', 'sendirian', 'adalah', 'oleh', 'terakhir', 'sangat', 'merasa', 'sepantasnyalah', 'bakalan', 'padanya', 
'tambah', 'kamulah', 'sekurang-kurangnya', 'sebesar', 'akhirnya', 'mula', 'sepertinya', 'diberikannya', 'menanyai', 'mulai', 
'lamanya', 'lain', 'menyampaikan', 'tertentu', 'ibarat', 'kedua', 'bilakah', 'sekadar', 'seluruh', 'tiap', 'tanpa', 'berapa', 
'akhiri', 'beberapa', 'dimulainya', 'dilihat', 'yaitu', 'hanya', 'pertanyakan', 'bawah', 'setidak-tidaknya', 'sewaktu', 
'inginkah', 'tandas', 'kalian', 'tuturnya', 'berapapun', 'setinggi', 'tidakkah', 'seberapa', 'sebisanya', 'tidaklah', 'ucap', 
'mulanya', 'ia', 'wah', 'cukuplah', 'waktu', 'tiba-tiba', 'beginian', 'belakangan', 'kelihatan', 'tunjuk', 'masa', 'toh', 
'sebutlah', 'kira', 'depan', 'misalnya', 'sebaliknya', 'sekiranya', 'sendirinya', 'semampu', 'bung', 'boleh', 'disinilah', 
'itu', 'kelima', 'merupakan', 'sebut', 'berturut-turut', 'tersebut', 'berkata', 'enggaknya', 'bagaimanapun', 'kamilah', 
'gunakan', 'setidaknya', 'ingat', 'segera', 'adanya', 'kami', 'dimulailah', 'sebagian', 'bermaksud', 'dilalui', 'ujar', 
'mereka', 'naik', 'biasanya', 'akan', 'sekadarnya', 'pak', 'sesampai', 'mampu', 'jadinya', 'disebutkan', 'yang', 'perlu', 
'walaupun', 'memperbuat', 'sekalian', 'tersebutlah', 'ditunjuk', 'seketika', 'bersama-sama', 'dimaksudkan', 'saja', 'paling', 
'pertama-tama', 'agak', 'itulah', 'menjelaskan', 'soalnya', 'panjang', 'berkenaan', 'bagian', 'semisalnya', 'maka', 'turut', 
'meyakinkan', 'saat', 'mempersiapkan', 'keduanya', 'demi', 'tanyakan', 'bersiap', 'melihatnya', 'amatlah', 'pernah', 'hanyalah', 
'menegaskan', 'kalaupun', 'ditunjuki', 'justru', 'ataupun', 'tadinya', 'digunakan', 'diantara', 'nyaris', 'mungkinkah']
