list_synonyms = {
    "durasi": ["lama"],
    "dilaksanakan": ["dilakukan"],
    "dilakukan": ["dilaksanakan"],
    "kondisi": ["keadaan"],
    "keadaan": ["kondisi"],
    "jabatan": ["posisi"],
    "posisi": ["jabatan"],
    "standar": ["umum"],
    "dipantau": ["diawasi"],
    "penggunaan": ["pemakaian"],
    "pemakaian": ["penggunaan"],
    "ancaman": ["bahaya"],
    "total": ["keseluruhan"],
    "keseluruhan": ["total"],
    "tugas": ["peran"],
    "melindungi": ["menjaga"],
    "kestabilan": ["stabilitas"],
    "opini": ["pandangan"],
    "bantuan ": ["dukungan"],
    "dana": ["anggaran"],
    "menangani": ["penanganan"],
    "syarat": ["persyaratan"],
    "prosedur": ["proses"],
}